# Development services for local development
# Use with: docker-compose -f docker-compose.dev.yml up
# This runs alongside pnpm dev for local development

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: todolist-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: todolist
    ports:
      - '27017:27017'
    volumes:
      - mongodb_dev_data:/data/db
      - ./docker/mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - todolist-dev-network
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_dev_data:
    driver: local

networks:
  todolist-dev-network:
    driver: bridge
